# Generated by Django 4.1.2 on 2022-11-04 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advocate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=50)),
                (
                    "profile_pic",
                    models.ImageField(default="avatar.png", upload_to="advocates"),
                ),
                ("short_bio", models.CharField(max_length=250)),
                ("long_bio", models.TextField()),
                ("advocate_years_exp", models.IntegerField()),
                ("youtube", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "logo",
                    models.ImageField(default="avatar.png", upload_to="companies"),
                ),
                ("summary", models.TextField()),
                ("youtube", models.URLField(blank=True, null=True)),
                ("twitter", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "advocates",
                    models.ManyToManyField(
                        blank=True,
                        related_name="companies_advocates",
                        to="api_edition.advocate",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="advocate",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="advocate_of_a_company",
                to="api_edition.company",
            ),
        ),
    ]
