# Generated by Django 4.1.2 on 2022-10-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_edition", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advocate",
            name="the_href",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="the_href",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
