# Generated by Django 4.1.2 on 2022-10-15 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api_edition", "0002_advocate_the_href_company_the_href"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advocate",
            old_name="the_href",
            new_name="url",
        ),
        migrations.RenameField(
            model_name="company",
            old_name="the_href",
            new_name="url",
        ),
    ]
