# Generated by Django 4.1.2 on 2022-10-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_edition", "0003_rename_the_href_advocate_url_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="github",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="twitter",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="youtube",
            field=models.URLField(blank=True, null=True),
        ),
    ]
