# Generated by Django 4.1.2 on 2022-10-17 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api_edition",
            "0004_company_github_company_linkedin_company_twitter_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="advocates",
            field=models.ManyToManyField(
                blank=True,
                related_name="companies_advocates",
                to="api_edition.advocate",
            ),
        ),
    ]
