# Generated by Django 4.1.2 on 2022-11-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_edition", "0005_alter_company_advocates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advocate",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
